export const ORDER_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  FAILED: 'FAILED',
  CANCELED: 'CANCELED',
  PENDING_REFUND: 'PENDING_REFUND',
  REFUNDED: 'REFUNDED',
  CHECKOUT: 'CHECKOUT',
  NO_SHOW: 'NO_SHOW',
} as const

export type OrderStatusType = (typeof ORDER_STATUS)[keyof typeof ORDER_STATUS]

export const MINIMUM_AMOUNT = 2000

export const REPUTATION_SCORE = {
  CHECKOUT_SUCCESS: 2,
  REVIEW_FROM_3: 3,
  REVIEW_LESS_3: -3,
  CANCEL_ORDER: 5,
}
